### ISSUE TITLE
Crashes when analyzing `eclipse/kapua`

### ISSUE THREAD

**Issue by bakhtos** [tuhh-softsec/code2DFD#11]
When trying to analyze `eclipse/kapua` project, the tools crashes:

```
Start extraction of DFD for eclipse/kapua at 13:55:49
Traceback (most recent call last):
  File "/Users/abakhtin22/Documents/TempNet/code2DFD/code2DFD.py", line 107, in <module>
    main()
  File "/Users/abakhtin22/Documents/TempNet/code2DFD/code2DFD.py", line 97, in main
    dfd_extraction.perform_analysis()
  File "/Users/abakhtin22/Documents/TempNet/code2DFD/core/dfd_extraction.py", line 62, in perform_analysis
    microservices = tech_sw.get_microservices(dfd)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abakhtin22/Documents/TempNet/code2DFD/core/technology_switch.py", line 26, in get_microservices
    mvn.set_microservices(dfd)
  File "/Users/abakhtin22/Documents/TempNet/code2DFD/technology_specific_extractors/maven/mvn_entry.py", line 38, in set_microservices
    microservice, properties = parse_configurations(pom_file)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abakhtin22/Documents/TempNet/code2DFD/technology_specific_extractors/maven/mvn_entry.py", line 132, in parse_configurations
    microservice = extract_servicename_pom_file(pom_file["content"], pom_file["path"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abakhtin22/Documents/TempNet/code2DFD/technology_specific_extractors/maven/mvn_entry.py", line 199, in extract_servicename_pom_file
    length_tuple = re.search(microservice[0], line).span()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'span'

```

**Comment by bakhtos** [comment]
Same error for `apolloconfig/apollo`

**Comment by bakhtos** [comment]
Same error with `zlt2000/microservices-platform`

**Comment by bakhtos** [comment]
Same error for `jeequan/jeepay`

**Comment by bakhtos** [comment]
Same error for `nageoffer/congomall`
