### ISSUE TITLE
Crashes when analyzing `weiraneve/seckillcloud`

### ISSUE THREAD

**Issue by bakhtos** [tuhh-softsec/code2DFD#15]
```

        Start extraction of DFD for weiraneve/seckillcloud at 14:18:49
Traceback (most recent call last):
  File "/Users/abakhtin22/Documents/TempNet/code2DFD/code2DFD.py", line 107, in <module>
    main()
  File "/Users/abakhtin22/Documents/TempNet/code2DFD/code2DFD.py", line 97, in main
    dfd_extraction.perform_analysis()
  File "/Users/abakhtin22/Documents/TempNet/code2DFD/core/dfd_extraction.py", line 62, in perform_analysis
    microservices = tech_sw.get_microservices(dfd)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abakhtin22/Documents/TempNet/code2DFD/core/technology_switch.py", line 26, in get_microservices
    mvn.set_microservices(dfd)
  File "/Users/abakhtin22/Documents/TempNet/code2DFD/technology_specific_extractors/maven/mvn_entry.py", line 77, in set_microservices
    tmp.tmp_config.set("DFD", "microservices", str(microservices))
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/configparser.py", line 1184, in set
    super().set(section, option, value)
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/configparser.py", line 872, in set
    value = self._interpolation.before_set(self, section, option,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/configparser.py", line 374, in before_set
    raise ValueError("invalid interpolation syntax in %r at "
ValueError: invalid interpolation syntax in "{0: {'servicename': 'cloud-uaa', 'image': 'image_placeholder', 'type': 'internal', 'pom_path': 'cloud-uaa/pom.xml', 'properties': {('port', 8088, ('./analysed_repositories/seckillcloud/cloud-uaa/src/main/resources/application.yml', 2, (8, 12)))}, 'stereotype_instances': [], 'tagged_values': []}, 1: {'servicename': 'cloud-gateway', 'image': 'image_placeholder', 'type': 'internal', 'pom_path': 'cloud-gateway/pom.xml', 'properties': {('spring_cloud_gateway_route', 'cloud-mission', ('./analysed_repositories/seckillcloud/cloud-gateway/src/main/resources/application.yml', 21, 'span')), ('spring_cloud_gateway_route', 'cloud-monitor', ('./analysed_repositories/seckillcloud/cloud-gateway/src/main/resources/application.yml', 21, 'span')), ('port', 8205, ('./analysed_repositories/seckillcloud/cloud-gateway/src/main/resources/application.yml', 3, (8, 12))), ('spring_cloud_gateway_route', 'cloud-manage', ('./analysed_repositories/seckillcloud/cloud-gateway/src/main/resources/application.yml', 21, 'span')), ('spring_cloud_gateway_route', 'cloud-uaa', ('./analysed_repositories/seckillcloud/cloud-gateway/src/main/resources/application.yml', 21, 'span')), ('circuit_breaker', 'Hystrix', ('file', 'line', 'span'))}, 'stereotype_instances': [], 'tagged_values': []}, 2: {'servicename': 'cloud-mission', 'image': 'image_placeholder', 'type': 'internal', 'pom_path': 'cloud-mission/pom.xml', 'properties': {('rabbit_password', 'guest', ('./analysed_repositories/seckillcloud/cloud-mission/src/main/resources/application.yml', 19, (15, 20))), ('port', 8888, ('./analysed_repositories/seckillcloud/cloud-mission/src/main/resources/application.yml', 2, (8, 12))), ('rabbit_username', 'guest', ('./analysed_repositories/seckillcloud/cloud-mission/src/main/resources/application.yml', 18, (15, 20)))}, 'stereotype_instances': [], 'tagged_values': []}, 3: {'servicename': 'pom_cloud-common', 'image': 'image_placeholder', 'type': 'internal', 'pom_path': 'cloud-common/pom.xml', 'properties': set(), 'stereotype_instances': [], 'tagged_values': []}, 4: {'servicename': 'pom_cloud-manage', 'image': 'image_placeholder', 'type': 'internal', 'pom_path': 'cloud-manage/pom.xml', 'properties': {('datasource_url', 'jdbc:mysql://${DOCKER_DB:localhost}:3306/cloud-manage?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true', ('./analysed_repositories/seckillcloud/cloud-manage/src/main/resources/application.yml', 11, (10, 191))), ('port', 8070, ('./analysed_repositories/seckillcloud/cloud-manage/src/main/resources/application.yml', 2, (8, 12)))}, 'stereotype_instances': [], 'tagged_values': []}, 5: {'servicename': 'cloud-monitor', 'image': 'image_placeholder', 'type': 'internal', 'pom_path': 'cloud-monitor/pom.xml', 'properties': {('port', 8890, ('./analysed_repositories/seckillcloud/cloud-monitor/src/main/resources/application.yml', 2, (8, 12)))}, 'stereotype_instances': [], 'tagged_values': []}}" at position 2325

```

**Comment by SimonAdrian** [comment]
Fixed by a83151524625eab96916ba20b868439f81c17ed3
