### ISSUE TITLE
`codeable_models` error for `ningzuoxin/exam-ning-springcloud-v1`

### ISSUE THREAD

**Issue by bakhtos** [tuhh-softsec/code2DFD#37]
Crashes when attempting to construct a `codeable_model`, OK otherwise:

```
Traceback (most recent call last):
  File "/Users/abakhtin22/Documents/TempNet/code2DFD/code2DFD.py", line 115, in <module>
    cli_invocation()
  File "/Users/abakhtin22/Documents/TempNet/code2DFD/code2DFD.py", line 111, in cli_invocation
    perform_analysis()
  File "/Users/abakhtin22/Documents/TempNet/code2DFD/core/dfd_extraction.py", line 74, in perform_analysis
    codeable_models, traceability_content = DFD_extraction()
                                            ^^^^^^^^^^^^^^^^
  File "/Users/abakhtin22/Documents/TempNet/code2DFD/core/dfd_extraction.py", line 156, in DFD_extraction
    visualizer.output_png(codeable_models_path)
  File "/Users/abakhtin22/Documents/TempNet/code2DFD/output_generators/visualizer.py", line 13, in output_png
    new_plantuml, new_plantuml_path = codeable_models_to_plantuml.convert(codeable_models_path)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abakhtin22/Documents/TempNet/code2DFD/output_generators/codeable_models_to_plantuml.py", line 39, in convert
    add_flow(line)
  File "/Users/abakhtin22/Documents/TempNet/code2DFD/output_generators/codeable_models_to_plantuml.py", line 169, in add_flow
    receiver = line.split("}")[0].split(":")[1].strip()
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by bakhtos** [comment]
Same for `paascloud/paascloud-master`
